<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYQlwPUY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYQlwPUY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYQlwPUY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYQlwPUY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYQlwPUY\App_KernelDevDebugContainer([
    'container.build_hash' => 'YQlwPUY',
    'container.build_id' => 'cb6c736e',
    'container.build_time' => 1716455704,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYQlwPUY');
