<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPQxhoAS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPQxhoAS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPQxhoAS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPQxhoAS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPQxhoAS\App_KernelDevDebugContainer([
    'container.build_hash' => 'PQxhoAS',
    'container.build_id' => 'af1d4c1a',
    'container.build_time' => 1714580582,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPQxhoAS');
