<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOtxcc2O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOtxcc2O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOtxcc2O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOtxcc2O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOtxcc2O\App_KernelDevDebugContainer([
    'container.build_hash' => 'Otxcc2O',
    'container.build_id' => 'cb9544ac',
    'container.build_time' => 1714729917,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOtxcc2O');
